### Testing ofrep
POST http://0.0.0.0:8080/ofrep/v1/evaluate/flags/FF-feature-flat-on-off
Content-Type: application/json

{}
###

### Testing ofrep
POST http://0.0.0.0:8080/ofrep/v1/evaluate/flags/FF-new-checkout
Content-Type: application/json

{
    "context": {
        "country": "GB",
        "platform": "web"
    }
}
###


### Testing ofrep
POST http://0.0.0.0:8080/ofrep/v1/evaluate/flags
Content-Type: application/json

{
    "context": {
        "countryCode": "nl"
    }
}
###