### Testing rest api
GET http://0.0.0.0:8080/v1/eval/FF-feature-flat-on-off
###

### Testing rest api
GET http://0.0.0.0:8080/v1/eval/FF-feature-flat-on-off?ff_output=plain
###

### Testing rest api with context
GET http://0.0.0.0:8080/v1/eval/FF-feature-y?countryCode=nl
###